### ISSUE TITLE
Can u help to generalise this code for different image_shape.

### ISSUE THREAD

**Issue by kunalr326** [Goldesel23/DCGAN-for-Bird-Generation#4]
Hey
U did a great job. I am using ur code to solve some problems.
Particularly (dcgan) code.
And I am getting errors while changing image_shape.
So can u suggest me where to update in the code to generalise it for different shapes of images.
Such as (128,128,3).
If possible can u please forward me the generalised version.

Thanks

**Comment by tensorfreitas** [comment]
Hi, 

Thank you for the kind words. 

To be able to generalize to bigger images for example (128, 128, 3) you can change the lines 83-86 to

```
generator.add(Dense(units=8 * 8 * 512,
                        kernel_initializer='glorot_uniform',
                        input_shape=(1, 1, 100)))
generator.add(Reshape(target_shape=(8, 8, 512))) 
```
and change the image_shape to  (128, 128, 3) and I think it will work (I don't have the possibility to test it right now). 

But be careful because traditional DCGANs have difficulties to converge to high resolution images, so you might need a more advanced method!
